### ISSUE TITLE
interactive interface not working

### ISSUE THREAD

**Issue by salmanfarisvp** [johnny-five-io/nodebots-interchange#26]
OS :- Windows 10
Board :- Arduino uno 

```

C:\Users\Faris\Documents\IOT\Johnny-Five\nodebots-interchange>node nodebots-interchange install --interactive
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Faris\Documents\IOT\Johnny-Five\nodebots-interchange\nodebots-interchange'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Comment by ajfisher** [comment]
Looks like you aren't calling it properly.

Install it with -g for a global install on Windows to get `interchange` or
instantiate it with `./node_modules/.bin/interchange` to run it locally.

Also, please ensure you've reviewed all the docs on the README which will
give you examples

**Comment by salmanfarisvp** [comment]
Thanks @ajfisher  , now working fine
