### ISSUE TITLE
Error: Sending 3020: receiveData timeout after 400ms

### ISSUE THREAD

**Issue by rwaldron** [johnny-five-io/nodebots-interchange#27]
```
$ ./node_modules/.bin/interchange install hc-sr04 -p /dev/cu.wchusbserial1410 -a nano
Installing hc-sr04 from npm
t2-hcsr04-backpack@0.0.0 /Users/rwaldron/robotz/t2-hcsr04-backpack
└── nodebots-hcsr04@0.5.0  (git+https://github.com/ajfisher/nodebots-hcsr04.git#357492677f4563a512436685199cfa661f4cf859)

connected
reset complete.
flashing, please wait...
flash complete.
Error: Sending 3020: receiveData timeout after 400ms
    at /Users/rwaldron/robotz/t2-hcsr04-backpack/node_modules/stk500/lib/sendCommand.js:36:17
    at finished (/Users/rwaldron/robotz/t2-hcsr04-backpack/node_modules/stk500/lib/receiveData.js:38:5)
    at Timeout._onTimeout (/Users/rwaldron/robotz/t2-hcsr04-backpack/node_modules/stk500/lib/receiveData.js:43:7)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by rwaldron** [comment]
Incidentally, here's what happens when using _just_ the IDE: 

```
ketch uses 10862 bytes (35%) of program storage space. Maximum is 30720 bytes.
Global variables use 677 bytes (33%) of dynamic memory, leaving 1371 bytes for local variables. Maximum is 2048 bytes.
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x00
An error occurred while uploading the sketch
```


So this is _not_ an issue with `nodebots-interchange`

**Comment by thebirdgr** [comment]
Hello,

What's the fix? I have this problem currently.

**Comment by ajfisher** [comment]
I can't really tell from that message an going to need some more
information.

What OS are you using, what type of Arduino are you using, what command did
you run, what firmware are you trying to flash?
